package com.mybatis.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbggenerated Wed Jun 15 21:36:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbggenerated Wed Jun 15 21:36:29 CST 2016
     */
    private String name;

    
    public Student(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbggenerated Wed Jun 15 21:36:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbggenerated Wed Jun 15 21:36:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbggenerated Wed Jun 15 21:36:29 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbggenerated Wed Jun 15 21:36:29 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}